### ISSUE TITLE
is this working for 1.10.0?

### ISSUE THREAD

**Issue by salsa2k** [codesouls/gulp-ember-template-compiler#5]
is this working for 1.10.0?

I got this message:
Uncaught Error: Assertion Failed: template must be a function. Did you mean to call Ember.Handlebars.compile("...") or specify templateName instead?

**Comment by karpinsn** [comment]
I'm getting the same issue, not sure whats up.

**Comment by Geodesigner** [comment]
Sorry, I will check it soon!

**Comment by karpinsn** [comment]
Figured it out. This package uses ember-template-compiler which is on '~1.9.0-alpha' and does not support Ember v.1.10.0. I manually modified it to use the compiler that is packaged with the latest release of ember, and it works. It compiles to HTMLBars which is the new template standard for Ember.
